final List<Map<String, dynamic>> music = [
  {
    "id": 0,
    "songName": "How Great Is Our God",
    "artist": "Chris Tomlin",
    "releaseYear": 2004,
    "album": "Arriving",
    "duration": "4:26",
    "image": "assets/images/songs/how_great_is_our_god.png",
    "audio": "assets/audio/how_great_is_our_god.mp3",
    "genre": "Worship",
    "key": "C",
    "bpm": 68,
    "keyTheme": "Majesty, Praise",
    "description": "A timeless anthem glorifying God's greatness.",
  },
  {
    "id": 1,
    "songName": "Way Maker",
    "artist": "Sinach / Leeland",
    "releaseYear": 2015,
    "album": "Way Maker (Live)",
    "duration": "4:45",
    "image": "assets/images/songs/way_maker.png",
    "audio": "assets/audio/way_maker.mp3",
    "genre": "Worship",
    "key": "E",
    "bpm": 70,
    "keyTheme": "Miracles, Presence",
    "description":
        "A global worship movement declaring God as miracle worker and light in the darkness.",
  },
  {
    "id": 2,
    "songName": "10,000 Reasons (Bless the Lord)",
    "artist": "Matt Redman",
    "releaseYear": 2011,
    "album": "10,000 Reasons",
    "duration": "4:22",
    "image": "assets/images/songs/10000_reasons.png",
    "audio": "assets/audio/10000_reasons.mp3",
    "genre": "Worship",
    "key": "G",
    "bpm": 73,
    "keyTheme": "Gratitude, Faithfulness",
    "description":
        "A stirring song reflecting a life of thankful worship inspired by Psalm 103.",
  },
  {
    "id": 3,
    "songName": "Reckless Love",
    "artist": "Cory Asbury",
    "releaseYear": 2017,
    "album": "Reckless Love",
    "duration": "5:31",
    "image": "assets/images/songs/reckless_love.png",
    "audio": "assets/audio/reckless_love.mp3",
    "genre": "Contemporary",
    "key": "G♭",
    "bpm": 83,
    "keyTheme": "God's Pursuit, Grace",
    "description":
        "A powerful narrative of God's unrelenting love, inspired by Luke 15.",
  },
  {
    "id": 4,
    "songName": "Who You Say I Am",
    "artist": "Hillsong Worship",
    "releaseYear": 2018,
    "album": "There Is More",
    "duration": "5:29",
    "image": "assets/images/songs/who_you_say_i_am.png",
    "audio": "assets/audio/who_you_say_i_am.mp3",
    "genre": "Worship",
    "key": "F",
    "bpm": 74,
    "keyTheme": "Identity, Freedom",
    "description":
        "Uplifting message of identity rooted in Christ, declaring freedom and belonging.",
  },
  {
    "id": 5,
    "songName": "Great Are You Lord",
    "artist": "All Sons & Daughters",
    "releaseYear": 2014,
    "album": "All Sons & Daughters",
    "duration": "4:25",
    "image": "assets/images/songs/great_are_you_lord.png",
    "audio": "assets/audio/great_are_you_lord.mp3",
    "genre": "Worship",
    "key": "A",
    "bpm": 72,
    "keyTheme": "Breath, Praise",
    "description":
        "A humble yet profound invitation to worship, declaring God's restorative power.",
  },
];
