final List<Map<String, dynamic>> music = [
  {
    "id": 0,
    "name": "How Great Is Our God",
    "artist": "Chris Tomlin",
    "releaseYear": 2004,
    "album": "Arriving",
    "duration": "4:26",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/how_great_is_our_god.png?updatedAt=1754059566710",
    "audio": "assets/audio/how_great_is_our_god.mp3",
    "genre": "Worship",
    "key": "C",
    "bpm": 68,
    "keyTheme": "Majesty, Praise",
    "description": "A timeless anthem glorifying God's greatness.",
    "isCotinueListening": true,
  },
  {
    "id": 1,
    "name": "Way Maker",
    "artist": "Sinach / Leeland",
    "releaseYear": 2015,
    "album": "Way Maker (Live)",
    "duration": "4:45",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/way_maker.png?updatedAt=1754059567147",
    "audio": "assets/audio/way_maker.mp3",
    "genre": "Worship",
    "key": "E",
    "bpm": 70,
    "keyTheme": "Miracles, Presence",
    "description":
        "A global worship movement declaring God as miracle worker and light in the darkness.",
    "isContinueListening": true,
  },
  {
    "id": 2,
    "name": "10,000 Reasons (Bless the Lord)",
    "artist": "Matt Redman",
    "releaseYear": 2011,
    "album": "10,000 Reasons",
    "duration": "4:22",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/10000_reasons.png?updatedAt=1754059567518",
    "audio": "assets/audio/10000_reasons.mp3",
    "genre": "Worship",
    "key": "G",
    "bpm": 73,
    "keyTheme": "Gratitude, Faithfulness",
    "description":
        "A stirring song reflecting a life of thankful worship inspired by Psalm 103.",
    "isContinueListening": true,
  },
  {
    "id": 3,
    "name": "Reckless Love",
    "artist": "Cory Asbury",
    "releaseYear": 2017,
    "album": "Reckless Love",
    "duration": "5:31",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/reckless_love.png?updatedAt=1754059566546",
    "audio": "assets/audio/reckless_love.mp3",
    "genre": "Contemporary",
    "key": "G♭",
    "bpm": 83,
    "keyTheme": "God's Pursuit, Grace",
    "description":
        "A powerful narrative of God's unrelenting love, inspired by Luke 15.",
    "isContinueListening": true,
  },
  {
    "id": 4,
    "name": "Who You Say I Am",
    "artist": "Hillsong Worship",
    "releaseYear": 2018,
    "album": "There Is More",
    "duration": "5:29",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/who_you_say_i_am.png?updatedAt=1754059566255",
    "audio": "assets/audio/who_you_say_i_am.mp3",
    "genre": "Worship",
    "key": "F",
    "bpm": 74,
    "keyTheme": "Identity, Freedom",
    "description":
        "Uplifting message of identity rooted in Christ, declaring freedom and belonging.",
    "isContinueListening": true,
  },
  {
    "id": 5,
    "name": "Great Are You Lord",
    "artist": "All Sons & Daughters",
    "releaseYear": 2014,
    "album": "All Sons & Daughters",
    "duration": "4:25",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/great_are_you_lord.png?updatedAt=1754059568216",
    "audio": "assets/audio/great_are_you_lord.mp3",
    "genre": "Worship",
    "key": "A",
    "bpm": 72,
    "keyTheme": "Breath, Praise",
    "description":
        "A humble yet profound invitation to worship, declaring God's restorative power.",
    "isContinueListening": true,
  },
  {
    "id": 6,
    "name": "Holy Forever",
    "artist": "Chris Tomlin",
    "releaseYear": 2022,
    "album": "Always",
    "duration": "5:08",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/holy_forever.png?updatedAt=1754059568547",
    "audio": "assets/audio/holy_forever.mp3",
    "genre": "Worship",
    "key": "D♭",
    "bpm": 72,
    "keyTheme": "Eternity, Holiness",
    "description":
        "A majestic anthem celebrating God's eternal holiness and glory.",
    "isContinueListening": false,
  },
  {
    "id": 7,
    "name": "Graves Into Gardens",
    "artist": "Elevation Worship",
    "releaseYear": 2020,
    "album": "Graves Into Gardens",
    "duration": "7:34",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/graves_into_garden.png?updatedAt=1754059568512",
    "audio": "assets/audio/graves_into_gardens.mp3",
    "genre": "Worship",
    "key": "B",
    "bpm": 70,
    "keyTheme": "Transformation, Triumph",
    "description":
        "Celebrates divine power to restore and renew, turning mourning into dancing.",
    "isContinueListening": false,
  },
  {
    "id": 8,
    "name": "Build My Life",
    "artist": "Pat Barrett",
    "releaseYear": 2018,
    "album": "Pat Barrett",
    "duration": "4:23",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/build_my_life.png?updatedAt=1754059568097",
    "audio": "assets/audio/build_my_life.mp3",
    "genre": "Worship",
    "key": "A♭",
    "bpm": 72,
    "keyTheme": "Surrender, Foundation",
    "description":
        "A prayerful posture of trust and devotion, inspired by Luke 6.",
    "isContinueListening": false,
  },
  {
    "id": 9,
    "name": "What An Awesome God",
    "artist": "Phil Wickham",
    "releaseYear": 2025,
    "album": "Song of the Saints",
    "duration": "4:20",
    "image":
        "https://ik.imagekit.io/j7iwyd9ys/Project%20SnowCone/what_an_awesome_god.png?updatedAt=1754059568142",
    "audio": "assets/audio/what_an_awesome_god.mp3",
    "genre": "Worship",
    "key": "D",
    "bpm": 76,
    "keyTheme": "Awe, Majesty",
    "description":
        "A modern revival of Rich Mullins’ classic chorus, declaring God's greatness with fresh verses.",
    "isContinueListening": false,
  },
];
