// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBKx38qii7rj46_qvqDU3hfYMbHL1sKehs",
    authDomain: "snowcone-f6759.firebaseapp.com",
    databaseURL: "https://snowcone-f6759-default-rtdb.firebaseio.com",
    projectId: "snowcone-f6759",
    storageBucket: "snowcone-f6759.firebasestorage.app",
    messagingSenderId: "63708234599",
    appId: "1:63708234599:web:bb18d61fac485cc6a765c2",
    measurementId: "G-BQ0R7K9PZR",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQLyWJRO_LU_7eI-RliDhUzykBXIAh9dQ',
    appId: '1:63708234599:android:228bcd9ab7f497e8a765c2',
    messagingSenderId: '63708234599',
    projectId: 'snowcone-f6759',
    storageBucket: 'snowcone-f6759.firebasestorage.app',
  );
}
