// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_raKNjEmh8sko5SAndmHjCUU-4Zeozs',
    appId: '1:475819000576:web:24e95a2300811e3e73e9e5',
    messagingSenderId: '475819000576',
    projectId: 'snowcone-45bcb',
    authDomain: 'snowcone-45bcb.firebaseapp.com',
    databaseURL: 'https://snowcone-45bcb-default-rtdb.firebaseio.com',
    storageBucket: 'snowcone-45bcb.firebasestorage.app',
    measurementId: 'G-H65BLNLVT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1crPLDK8BGmTH6fLFSgxLxFXa7jHTzqU',
    appId: '1:475819000576:android:771388648791232273e9e5',
    messagingSenderId: '475819000576',
    projectId: 'snowcone-45bcb',
    databaseURL: 'https://snowcone-45bcb-default-rtdb.firebaseio.com',
    storageBucket: 'snowcone-45bcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXmxdDFOCC0gSD5j6VDhyaNxdOdwS0LeU',
    appId: '1:475819000576:ios:1454ca9a2a45b86173e9e5',
    messagingSenderId: '475819000576',
    projectId: 'snowcone-45bcb',
    databaseURL: 'https://snowcone-45bcb-default-rtdb.firebaseio.com',
    storageBucket: 'snowcone-45bcb.firebasestorage.app',
    iosBundleId: 'com.example.snowcone.snowcone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXmxdDFOCC0gSD5j6VDhyaNxdOdwS0LeU',
    appId: '1:475819000576:ios:1454ca9a2a45b86173e9e5',
    messagingSenderId: '475819000576',
    projectId: 'snowcone-45bcb',
    databaseURL: 'https://snowcone-45bcb-default-rtdb.firebaseio.com',
    storageBucket: 'snowcone-45bcb.firebasestorage.app',
    iosBundleId: 'com.example.snowcone.snowcone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_raKNjEmh8sko5SAndmHjCUU-4Zeozs',
    appId: '1:475819000576:web:b549cc7fc8bc0ecf73e9e5',
    messagingSenderId: '475819000576',
    projectId: 'snowcone-45bcb',
    authDomain: 'snowcone-45bcb.firebaseapp.com',
    databaseURL: 'https://snowcone-45bcb-default-rtdb.firebaseio.com',
    storageBucket: 'snowcone-45bcb.firebasestorage.app',
    measurementId: 'G-TYNTMXY7FZ',
  );
}
